### ISSUE TITLE
`--output-directory` not used on bash for windows

### ISSUE THREAD

**Issue by Chocrates** [timrogers/gh-sizer#51]
This command should presumably put the files in the directory `results` 
`gh sizer generate-script gh-sizer-sandbox --output-directory results --output-filename "${owner}-${repository}.txt"`

Instead the files are created in the current directory like this `resultsgh-sizer-sandbox-second-repo`

**Comment by timrogers** [comment]
@Chocrates Thanks for flagging this! Could you please share an example of the script that is generated?

**Comment by timrogers** [comment]
I tried this on my machine on macOS, and I get a script that looks like this:

```
#!/usr/bin/env bash

# Script generated by gh-sizer v0.2.0

mkdir -p results
echo "Processing repo gh-sizer-sandbox/second-repo (1/2)"
gh sizer repo gh-sizer-sandbox/second-repo --output-format text > results/gh-sizer-sandbox-second-repo.txt
echo "Processing repo gh-sizer-sandbox/first-repo (2/2)"
gh sizer repo gh-sizer-sandbox/first-repo --output-format text > results/gh-sizer-sandbox-first-repo.txt


# Script generated by gh-sizer v0.2.0
```

I'm guessing the Windows script must look different!

**Comment by timrogers** [comment]
I think the cause of this will be somehow related to the behaviour of Rust's `PathBuf` on Windows and how that interacts with Bash for Windows.

**Comment by Chocrates** [comment]
I will ask the customer for a copy, I didn't save it.  
I think the script generated fine but on windows/bash the `results/gh-sizer...` bit doesn't understand the path delimiter on windows or something.

**Comment by timrogers** [comment]
Interesting! I'd love to see a copy - or otherwise I can try to boot up my Windows machine when I have some more time.
